<?php

declare(strict_types=1);

namespace Seatplus\EsiSchema\Resources;

use Seatplus\EsiSchema\Contracts\EsiTransportInterface;
use Seatplus\EsiSchema\Resources\Cosmetics\GetCharactersCosmeticsSkinr;
use Seatplus\EsiSchema\Responses\CharactersCosmeticsSkinr;
use Seatplus\EsiSchema\Resources\Cosmetics\GetCharactersCosmeticsSkinrComponents;
use Seatplus\EsiSchema\Responses\CharactersCosmeticsSkinrComponents;
use Seatplus\EsiSchema\Resources\Cosmetics\GetCosmeticsSkinr;
use Seatplus\EsiSchema\Responses\CosmeticsSkinr;

/**
 * ESI Cosmetics resource — fluent wrapper around per-route static classes.
 *
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CosmeticsResource
{
    public function __construct(private readonly EsiTransportInterface $transport)
    {
    }

    /**
     * @return CharactersCosmeticsSkinr
     * @scope esi.cosmetic.char:read
     */
    public function getCharactersCosmeticsSkinr(int $characterId): CharactersCosmeticsSkinr
    {
        return GetCharactersCosmeticsSkinr::execute($this->transport, $characterId);
    }

    /**
     * @return CharactersCosmeticsSkinrComponents
     * @scope esi.cosmetic.char:read
     */
    public function getCharactersCosmeticsSkinrComponents(int $characterId): CharactersCosmeticsSkinrComponents
    {
        return GetCharactersCosmeticsSkinrComponents::execute($this->transport, $characterId);
    }

    /**
     * @return CosmeticsSkinr
     */
    public function getCosmeticsSkinr(string $skinrId): CosmeticsSkinr
    {
        return GetCosmeticsSkinr::execute($this->transport, $skinrId);
    }
}
