<?php

declare(strict_types=1);

namespace Seatplus\EsiSchema\Resources;

use Seatplus\EsiSchema\Contracts\EsiTransportInterface;
use Seatplus\EsiSchema\Resources\Location\GetCharactersCharacterIdLocation;
use Seatplus\EsiSchema\Responses\CharactersLocation;
use Seatplus\EsiSchema\Resources\Location\GetCharactersCharacterIdOnline;
use Seatplus\EsiSchema\Responses\CharactersOnline;
use Seatplus\EsiSchema\Resources\Location\GetCharactersCharacterIdShip;
use Seatplus\EsiSchema\Responses\CharactersShip;

/**
 * ESI Location resource — fluent wrapper around per-route static classes.
 *
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class LocationResource
{
    public function __construct(private readonly EsiTransportInterface $transport)
    {
    }

    /**
     * @return CharactersLocation
     * @scope esi-location.read_location.v1
     */
    public function getCharactersCharacterIdLocation(int $characterId): CharactersLocation
    {
        return GetCharactersCharacterIdLocation::execute($this->transport, $characterId);
    }

    /**
     * @return CharactersOnline
     * @scope esi-location.read_online.v1
     */
    public function getCharactersCharacterIdOnline(int $characterId): CharactersOnline
    {
        return GetCharactersCharacterIdOnline::execute($this->transport, $characterId);
    }

    /**
     * @return CharactersShip
     * @scope esi-location.read_ship_type.v1
     */
    public function getCharactersCharacterIdShip(int $characterId): CharactersShip
    {
        return GetCharactersCharacterIdShip::execute($this->transport, $characterId);
    }
}
