<?php

declare(strict_types=1);

namespace Seatplus\EsiSchema\Resources;

use Seatplus\EsiSchema\Contracts\EsiTransportInterface;
use Seatplus\EsiSchema\Resources\Meta\GetMetaChangelog;
use Seatplus\EsiSchema\Responses\MetaChangelog;
use Seatplus\EsiSchema\Resources\Meta\GetMetaCompatibilityDates;
use Seatplus\EsiSchema\Responses\MetaCompatibilityDates;
use Seatplus\EsiSchema\Resources\Meta\GetMetaName;
use Seatplus\EsiSchema\Responses\MetaName;
use Seatplus\EsiSchema\Resources\Meta\GetMetaStatus;
use Seatplus\EsiSchema\Responses\MetaStatus;

/**
 * ESI Meta resource — fluent wrapper around per-route static classes.
 *
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class MetaResource
{
    public function __construct(private readonly EsiTransportInterface $transport)
    {
    }

    /**
     * @return MetaChangelog
     */
    public function getMetaChangelog(): MetaChangelog
    {
        return GetMetaChangelog::execute($this->transport);
    }

    /**
     * @return MetaCompatibilityDates
     */
    public function getMetaCompatibilityDates(): MetaCompatibilityDates
    {
        return GetMetaCompatibilityDates::execute($this->transport);
    }

    /**
     * @return MetaName
     */
    public function getMetaName(): MetaName
    {
        return GetMetaName::execute($this->transport);
    }

    /**
     * @return MetaStatus
     */
    public function getMetaStatus(): MetaStatus
    {
        return GetMetaStatus::execute($this->transport);
    }
}
