<?php

declare(strict_types=1);

namespace Seatplus\EsiSchema\Resources;

use Seatplus\EsiSchema\Contracts\EsiTransportInterface;
use Seatplus\EsiSchema\Resources\MilitaryCampaigns\GetCharactersMilitaryCampaignsObjectivesListing;
use Seatplus\EsiSchema\Responses\CharactersMilitaryCampaignsObjectivesListing;
use Seatplus\EsiSchema\Resources\MilitaryCampaigns\GetCharactersMilitaryCampaignsObjectivesParticipation;
use Seatplus\EsiSchema\Responses\CharactersMilitaryCampaignsObjectivesParticipation;
use Seatplus\EsiSchema\Resources\MilitaryCampaigns\GetMilitaryCampaignsListing;
use Seatplus\EsiSchema\Responses\MilitaryCampaignsListing;
use Seatplus\EsiSchema\Resources\MilitaryCampaigns\GetMilitaryCampaignsDetail;
use Seatplus\EsiSchema\Responses\MilitaryCampaignsDetail;
use Seatplus\EsiSchema\Resources\MilitaryCampaigns\GetMilitaryCampaignsObjectivesListing;
use Seatplus\EsiSchema\Responses\MilitaryCampaignsObjectivesListing;
use Seatplus\EsiSchema\Resources\MilitaryCampaigns\GetMilitaryCampaignsObjectivesDetail;
use Seatplus\EsiSchema\Responses\MilitaryCampaignsObjectivesDetail;

/**
 * ESI MilitaryCampaigns resource — fluent wrapper around per-route static classes.
 *
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class MilitaryCampaignsResource
{
    public function __construct(private readonly EsiTransportInterface $transport)
    {
    }

    /**
     * @return CharactersMilitaryCampaignsObjectivesListing
     * @scope esi.activity.char:read
     */
    public function getCharactersMilitaryCampaignsObjectivesListing(int $characterId, ?string $after = null, ?string $before = null, ?int $limit = null): CharactersMilitaryCampaignsObjectivesListing
    {
        return GetCharactersMilitaryCampaignsObjectivesListing::execute($this->transport, $characterId, $after, $before, $limit);
    }

    /**
     * @return CharactersMilitaryCampaignsObjectivesParticipation
     * @scope esi.activity.char:read
     */
    public function getCharactersMilitaryCampaignsObjectivesParticipation(int $characterId, string $objectiveId): CharactersMilitaryCampaignsObjectivesParticipation
    {
        return GetCharactersMilitaryCampaignsObjectivesParticipation::execute($this->transport, $characterId, $objectiveId);
    }

    /**
     * @return MilitaryCampaignsListing
     */
    public function getMilitaryCampaignsListing(): MilitaryCampaignsListing
    {
        return GetMilitaryCampaignsListing::execute($this->transport);
    }

    /**
     * @return MilitaryCampaignsDetail
     */
    public function getMilitaryCampaignsDetail(string $campaignId): MilitaryCampaignsDetail
    {
        return GetMilitaryCampaignsDetail::execute($this->transport, $campaignId);
    }

    /**
     * @return MilitaryCampaignsObjectivesListing
     */
    public function getMilitaryCampaignsObjectivesListing(string $campaignId, ?string $after = null, ?string $before = null, ?int $limit = null): MilitaryCampaignsObjectivesListing
    {
        return GetMilitaryCampaignsObjectivesListing::execute($this->transport, $campaignId, $after, $before, $limit);
    }

    /**
     * @return MilitaryCampaignsObjectivesDetail
     */
    public function getMilitaryCampaignsObjectivesDetail(string $campaignId, string $objectiveId): MilitaryCampaignsObjectivesDetail
    {
        return GetMilitaryCampaignsObjectivesDetail::execute($this->transport, $campaignId, $objectiveId);
    }
}
