<?php

declare(strict_types=1);

namespace Seatplus\EsiSchema\Resources;

use Seatplus\EsiSchema\Contracts\EsiTransportInterface;
use Seatplus\EsiSchema\Resources\ParagonHub\GetCharactersParagonHubSkinr;
use Seatplus\EsiSchema\Responses\CharactersParagonHubSkinr;
use Seatplus\EsiSchema\Resources\ParagonHub\GetParagonHubSkinr;
use Seatplus\EsiSchema\Responses\ParagonHubSkinr;
use Seatplus\EsiSchema\Resources\ParagonHub\GetParagonHubSkinrAlliances;
use Seatplus\EsiSchema\Responses\ParagonHubSkinrAlliances;
use Seatplus\EsiSchema\Resources\ParagonHub\GetParagonHubSkinrCharacters;
use Seatplus\EsiSchema\Responses\ParagonHubSkinrCharacters;
use Seatplus\EsiSchema\Resources\ParagonHub\GetParagonHubSkinrCorporations;
use Seatplus\EsiSchema\Responses\ParagonHubSkinrCorporations;

/**
 * ESI ParagonHub resource — fluent wrapper around per-route static classes.
 *
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class ParagonHubResource
{
    public function __construct(private readonly EsiTransportInterface $transport)
    {
    }

    /**
     * @return CharactersParagonHubSkinr
     * @scope esi.cosmetic.char:read
     */
    public function getCharactersParagonHubSkinr(int $characterId, ?string $after = null, ?string $before = null, ?int $limit = null): CharactersParagonHubSkinr
    {
        return GetCharactersParagonHubSkinr::execute($this->transport, $characterId, $after, $before, $limit);
    }

    /**
     * @return ParagonHubSkinr
     */
    public function getParagonHubSkinr(?string $after = null, ?string $before = null, ?int $limit = null): ParagonHubSkinr
    {
        return GetParagonHubSkinr::execute($this->transport, $after, $before, $limit);
    }

    /**
     * @return ParagonHubSkinrAlliances
     * @scope esi.cosmetic.char:read
     */
    public function getParagonHubSkinrAlliances(int $allianceId, ?string $after = null, ?string $before = null, ?int $limit = null): ParagonHubSkinrAlliances
    {
        return GetParagonHubSkinrAlliances::execute($this->transport, $allianceId, $after, $before, $limit);
    }

    /**
     * @return ParagonHubSkinrCharacters
     * @scope esi.cosmetic.char:read
     */
    public function getParagonHubSkinrCharacters(int $characterId, ?string $after = null, ?string $before = null, ?int $limit = null): ParagonHubSkinrCharacters
    {
        return GetParagonHubSkinrCharacters::execute($this->transport, $characterId, $after, $before, $limit);
    }

    /**
     * @return ParagonHubSkinrCorporations
     * @scope esi.cosmetic.char:read
     */
    public function getParagonHubSkinrCorporations(int $corporationId, ?string $after = null, ?string $before = null, ?int $limit = null): ParagonHubSkinrCorporations
    {
        return GetParagonHubSkinrCorporations::execute($this->transport, $corporationId, $after, $before, $limit);
    }
}
