<?php

declare(strict_types=1);

namespace Seatplus\EsiSchema\Resources;

use Seatplus\EsiSchema\Contracts\EsiTransportInterface;
use Seatplus\EsiSchema\Resources\Status\GetStatus;
use Seatplus\EsiSchema\Responses\Status;

/**
 * ESI Status resource — fluent wrapper around per-route static classes.
 *
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class StatusResource
{
    public function __construct(private readonly EsiTransportInterface $transport)
    {
    }

    /**
     * @return Status
     */
    public function getStatus(): Status
    {
        return GetStatus::execute($this->transport);
    }
}
