<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class AlliancesAllianceIdContactsLabelsGetItem extends AbstractEsiDto
{
    public function __construct(
        public readonly int $label_id,
        public readonly string $label_name,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            label_id: (int) ($data->label_id ?? 0),
            label_name: (string) ($data->label_name ?? ''),
        );
    }
}
