<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersStructuresMercenaryDensDetailEvolutiondevelopment extends AbstractEsiDto
{
    public function __construct(
        public readonly int $amount,
        public readonly string $level,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            amount: (int) ($data->amount ?? 0),
            level: (string) ($data->level ?? ''),
        );
    }
}
