<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersCharacterIdCalendarEventIdAttendeesGetItem extends AbstractEsiDto
{
    public function __construct(
        public readonly ?int $character_id = null,
        public readonly ?string $event_response = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            character_id: $data->character_id ?? null,
            event_response: $data->event_response ?? null,
        );
    }
}
