<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersCosmeticsSkinrItem extends AbstractEsiDto
{
    public function __construct(
        public readonly bool $activated,
        public readonly string $skinr_id,
        public readonly int $unactivated,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            activated: (bool) ($data->activated ?? false),
            skinr_id: (string) ($data->skinr_id ?? ''),
            unactivated: (int) ($data->unactivated ?? 0),
        );
    }
}
