<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersMilitaryCampaignsObjectivesParticipation extends AbstractEsiDto
{
    public function __construct(
        public readonly string $campaign_id,
        public readonly int $contributed,
        public readonly string $id,
        public readonly bool $is_committed,
        public readonly string $last_modified,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            campaign_id: (string) ($data->campaign_id ?? ''),
            contributed: (int) ($data->contributed ?? 0),
            id: (string) ($data->id ?? ''),
            is_committed: (bool) ($data->is_committed ?? false),
            last_modified: (string) ($data->last_modified ?? ''),
        );
    }
}
