<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersMilitaryCampaignsObjectivesListing extends AbstractEsiDto
{
    public function __construct(
        public readonly array $objectives,
        public readonly ?Cursor $cursor = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            objectives: array_map(fn (object $i) => CharactersMilitaryCampaignsObjectivesParticipationCharacterobjective::from($i), (array) ($data->objectives ?? [])),
            cursor: isset($data->cursor) ? Cursor::from($data->cursor) : null,
        );
    }
}
