<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersFreelanceJobsListing extends AbstractEsiDto
{
    public function __construct(
        public readonly array $freelance_jobs,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            freelance_jobs: array_map(fn (object $i) => FreelanceJobsDetailFreelancejob::from($i), (array) ($data->freelance_jobs ?? [])),
        );
    }
}
