<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersStructuresMercenaryDensListingMercenaryden extends AbstractEsiDto
{
    public function __construct(
        public readonly int $id,
        public readonly int $planet_id,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            id: (int) ($data->id ?? 0),
            planet_id: (int) ($data->planet_id ?? 0),
        );
    }
}
