<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersStructuresMercenaryDensDetailEvolution extends AbstractEsiDto
{
    public function __construct(
        public readonly CharactersStructuresMercenaryDensDetailEvolutionanarchy $anarchy,
        public readonly CharactersStructuresMercenaryDensDetailEvolutiondevelopment $development,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            anarchy: CharactersStructuresMercenaryDensDetailEvolutionanarchy::from($data->anarchy ?? new \stdClass()),
            development: CharactersStructuresMercenaryDensDetailEvolutiondevelopment::from($data->development ?? new \stdClass()),
        );
    }
}
