<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersLocation extends AbstractEsiDto
{
    public function __construct(
        public readonly int $solar_system_id,
        public readonly ?int $station_id = null,
        public readonly ?int $structure_id = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            solar_system_id: (int) ($data->solar_system_id ?? 0),
            station_id: $data->station_id ?? null,
            structure_id: $data->structure_id ?? null,
        );
    }
}
