<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersCharacterIdStandingsGetItem extends AbstractEsiDto
{
    public function __construct(
        public readonly int $from_id,
        public readonly string $from_type,
        public readonly float $standing,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            from_id: (int) ($data->from_id ?? 0),
            from_type: (string) ($data->from_type ?? ''),
            standing: (float) ($data->standing ?? 0.0),
        );
    }
}
