<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersAccessListsListing extends AbstractEsiDto
{
    public function __construct(
        public readonly array $access_lists,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            access_lists: array_map(fn (object $i) => CharactersAccessListsListingAccesslist::from($i), (array) ($data->access_lists ?? [])),
        );
    }
}
