<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersCharacterIdFittingsPost extends AbstractEsiDto
{
    public function __construct(
        public readonly int $fitting_id,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            fitting_id: (int) ($data->fitting_id ?? 0),
        );
    }
}
