<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersCharacterIdKillmailsRecentGetItem extends AbstractEsiDto
{
    public function __construct(
        public readonly string $killmail_hash,
        public readonly int $killmail_id,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            killmail_hash: (string) ($data->killmail_hash ?? ''),
            killmail_id: (int) ($data->killmail_id ?? 0),
        );
    }
}
