<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersCosmeticsSkinrComponentsItem extends AbstractEsiDto
{
    public function __construct(
        public readonly int $component_id,
        public readonly mixed $runs,
        public readonly string $type,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            component_id: (int) ($data->component_id ?? 0),
            runs: ($data->runs ?? null),
            type: (string) ($data->type ?? ''),
        );
    }
}
