<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersStructuresMercenaryDensListing extends AbstractEsiDto
{
    public function __construct(
        public readonly array $mercenary_dens,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            mercenary_dens: array_map(fn (object $i) => CharactersStructuresMercenaryDensListingMercenaryden::from($i), (array) ($data->mercenary_dens ?? [])),
        );
    }
}
