<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersShip extends AbstractEsiDto
{
    public function __construct(
        public readonly int $ship_item_id,
        public readonly string $ship_name,
        public readonly int $ship_type_id,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            ship_item_id: (int) ($data->ship_item_id ?? 0),
            ship_name: (string) ($data->ship_name ?? ''),
            ship_type_id: (int) ($data->ship_type_id ?? 0),
        );
    }
}
