<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CharactersStructuresMercenaryDensDetailReinforcementtimer extends AbstractEsiDto
{
    public function __construct(
        public readonly string $end,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            end: (string) ($data->end ?? ''),
        );
    }
}
