<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CorporationsStructuresSovereigntyHubsDetailResources extends AbstractEsiDto
{
    public function __construct(
        public readonly CorporationsStructuresSovereigntyHubsDetailResourcepower $power,
        public readonly CorporationsStructuresSovereigntyHubsDetailResourceworkforce $workforce,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            power: CorporationsStructuresSovereigntyHubsDetailResourcepower::from($data->power ?? new \stdClass()),
            workforce: CorporationsStructuresSovereigntyHubsDetailResourceworkforce::from($data->workforce ?? new \stdClass()),
        );
    }
}
