<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CorporationsProjectsDetailContribution extends AbstractEsiDto
{
    public function __construct(
        public readonly ?int $participation_limit = null,
        public readonly ?float $reward_per_contribution = null,
        public readonly ?int $submission_limit = null,
        public readonly ?float $submission_multiplier = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            participation_limit: $data->participation_limit ?? null,
            reward_per_contribution: $data->reward_per_contribution ?? null,
            submission_limit: $data->submission_limit ?? null,
            submission_multiplier: $data->submission_multiplier ?? null,
        );
    }
}
