<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CorporationsDetailTaxrates extends AbstractEsiDto
{
    public function __construct(
        public readonly float $isk,
        public readonly float $loyalty_point,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            isk: (float) ($data->isk ?? 0.0),
            loyalty_point: (float) ($data->loyalty_point ?? 0.0),
        );
    }
}
