<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CorporationsStructuresSkyhooksListing extends AbstractEsiDto
{
    public function __construct(
        public readonly array $skyhooks,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            skyhooks: array_map(fn (object $i) => CorporationsStructuresSkyhooksListingSkyhook::from($i), (array) ($data->skyhooks ?? [])),
        );
    }
}
