<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CorporationsStructuresSovereigntyHubsListing extends AbstractEsiDto
{
    public function __construct(
        public readonly array $sovereignty_hubs,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            sovereignty_hubs: array_map(fn (object $i) => CorporationsStructuresSovereigntyHubsListingSovereigntyhub::from($i), (array) ($data->sovereignty_hubs ?? [])),
        );
    }
}
