<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CorporationsCorporationIdMembersTitlesGetItem extends AbstractEsiDto
{
    public function __construct(
        public readonly int $character_id,
        public readonly array $titles,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            character_id: (int) ($data->character_id ?? 0),
            titles: (array) ($data->titles ?? []),
        );
    }
}
