<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CorporationsProjectsDetailConfigurationminematerial extends AbstractEsiDto
{
    public function __construct(
        public readonly ?array $locations = null,
        public readonly ?array $materials = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            locations: isset($data->locations) ? (array) $data->locations : null,
            materials: isset($data->materials) ? (array) $data->materials : null,
        );
    }
}
