<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CosmeticsSkinrPatterntransform extends AbstractEsiDto
{
    public function __construct(
        public readonly CosmeticsSkinrVector3 $position,
        public readonly CosmeticsSkinrVector4 $rotation,
        public readonly CosmeticsSkinrVector3 $scaling,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            position: CosmeticsSkinrVector3::from($data->position ?? new \stdClass()),
            rotation: CosmeticsSkinrVector4::from($data->rotation ?? new \stdClass()),
            scaling: CosmeticsSkinrVector3::from($data->scaling ?? new \stdClass()),
        );
    }
}
