<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CosmeticsSkinr extends AbstractEsiDto
{
    public function __construct(
        public readonly int $creator_id,
        public readonly string $id,
        public readonly CosmeticsSkinrLayout $layout,
        public readonly string $name,
        public readonly int $ship_type_id,
        public readonly CosmeticsSkinrTier $tier,
        public readonly ?string $line = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            creator_id: (int) ($data->creator_id ?? 0),
            id: (string) ($data->id ?? ''),
            layout: CosmeticsSkinrLayout::from($data->layout ?? new \stdClass()),
            name: (string) ($data->name ?? ''),
            ship_type_id: (int) ($data->ship_type_id ?? 0),
            tier: CosmeticsSkinrTier::from($data->tier ?? new \stdClass()),
            line: $data->line ?? null,
        );
    }
}
