<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CosmeticsSkinrPatternprojection extends AbstractEsiDto
{
    public function __construct(
        public readonly bool $slot1,
        public readonly bool $slot2,
        public readonly bool $slot3,
        public readonly bool $slot4,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            slot1: (bool) ($data->slot1 ?? false),
            slot2: (bool) ($data->slot2 ?? false),
            slot3: (bool) ($data->slot3 ?? false),
            slot4: (bool) ($data->slot4 ?? false),
        );
    }
}
