<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CosmeticsSkinrSlotpattern extends AbstractEsiDto
{
    public function __construct(
        public readonly CosmeticsSkinrPatternconfiguration $configuration,
        public readonly int $id,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            configuration: CosmeticsSkinrPatternconfiguration::from($data->configuration ?? new \stdClass()),
            id: (int) ($data->id ?? 0),
        );
    }
}
