<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CosmeticsSkinrVector4 extends AbstractEsiDto
{
    public function __construct(
        public readonly float $w,
        public readonly float $x,
        public readonly float $y,
        public readonly float $z,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            w: (float) ($data->w ?? 0.0),
            x: (float) ($data->x ?? 0.0),
            y: (float) ($data->y ?? 0.0),
            z: (float) ($data->z ?? 0.0),
        );
    }
}
