<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CosmeticsSkinrPatternconfiguration extends AbstractEsiDto
{
    public function __construct(
        public readonly bool $mirrored,
        public readonly CosmeticsSkinrPatternprojection $projection,
        public readonly CosmeticsSkinrPatterntransform $transform,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            mirrored: (bool) ($data->mirrored ?? false),
            projection: CosmeticsSkinrPatternprojection::from($data->projection ?? new \stdClass()),
            transform: CosmeticsSkinrPatterntransform::from($data->transform ?? new \stdClass()),
        );
    }
}
