<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class CosmeticsSkinrLayout extends AbstractEsiDto
{
    public function __construct(
        public readonly string $pattern_blend_mode,
        public readonly array $slots,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            pattern_blend_mode: (string) ($data->pattern_blend_mode ?? ''),
            slots: array_map(fn (object $i) => CosmeticsSkinrLayoutslot::from($i), (array) ($data->slots ?? [])),
        );
    }
}
