<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class FleetsFleetIdGet extends AbstractEsiDto
{
    public function __construct(
        public readonly bool $is_free_move,
        public readonly bool $is_registered,
        public readonly bool $is_voice_enabled,
        public readonly string $motd,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            is_free_move: (bool) ($data->is_free_move ?? false),
            is_registered: (bool) ($data->is_registered ?? false),
            is_voice_enabled: (bool) ($data->is_voice_enabled ?? false),
            motd: (string) ($data->motd ?? ''),
        );
    }
}
