<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class FreelanceJobsDetailProgress extends AbstractEsiDto
{
    public function __construct(
        public readonly int $current,
        public readonly int $desired,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            current: (int) ($data->current ?? 0),
            desired: (int) ($data->desired ?? 0),
        );
    }
}
