<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class FreelanceJobsDetailCreator extends AbstractEsiDto
{
    public function __construct(
        public readonly FreelanceJobsDetailCreatorcharacter $character,
        public readonly FreelanceJobsDetailCreatorcorporation $corporation,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            character: FreelanceJobsDetailCreatorcharacter::from($data->character ?? new \stdClass()),
            corporation: FreelanceJobsDetailCreatorcorporation::from($data->corporation ?? new \stdClass()),
        );
    }
}
