<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class MarketsPricesGetItem extends AbstractEsiDto
{
    public function __construct(
        public readonly int $type_id,
        public readonly ?float $adjusted_price = null,
        public readonly ?float $average_price = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            type_id: (int) ($data->type_id ?? 0),
            adjusted_price: $data->adjusted_price ?? null,
            average_price: $data->average_price ?? null,
        );
    }
}
