<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class MetaChangelog extends AbstractEsiDto
{
    public function __construct(
        public readonly mixed $changelog,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            changelog: ($data->changelog ?? null),
        );
    }
}
