<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class MetaStatusRoutestatus extends AbstractEsiDto
{
    public function __construct(
        public readonly string $method,
        public readonly string $path,
        public readonly string $status,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            method: (string) ($data->method ?? ''),
            path: (string) ($data->path ?? ''),
            status: (string) ($data->status ?? ''),
        );
    }
}
