<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class MetaCompatibilityDates extends AbstractEsiDto
{
    public function __construct(
        public readonly array $compatibility_dates,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            compatibility_dates: (array) ($data->compatibility_dates ?? []),
        );
    }
}
