<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class MilitaryCampaignsObjectivesDetailObjective extends AbstractEsiDto
{
    public function __construct(
        public readonly string $id,
        public readonly string $last_modified,
        public readonly MilitaryCampaignsObjectivesDetailParticipants $participants,
        public readonly int $progress,
        public readonly string $state,
        public readonly ?string $finished = null,
        public readonly ?string $started = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            id: (string) ($data->id ?? ''),
            last_modified: (string) ($data->last_modified ?? ''),
            participants: MilitaryCampaignsObjectivesDetailParticipants::from($data->participants ?? new \stdClass()),
            progress: (int) ($data->progress ?? 0),
            state: (string) ($data->state ?? ''),
            finished: $data->finished ?? null,
            started: $data->started ?? null,
        );
    }
}
