<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class MilitaryCampaignsObjectivesDetailParticipants extends AbstractEsiDto
{
    public function __construct(
        public readonly int $committed,
        public readonly int $contributors,
        public readonly int $total,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            committed: (int) ($data->committed ?? 0),
            contributors: (int) ($data->contributors ?? 0),
            total: (int) ($data->total ?? 0),
        );
    }
}
