<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class ParagonHubSkinrInternalItem extends AbstractEsiDto
{
    public function __construct(
        public readonly string $created,
        public readonly string $expires,
        public readonly string $id,
        public readonly string $last_modified,
        public readonly mixed $price,
        public readonly int $quantity,
        public readonly int $seller_id,
        public readonly string $skinr_id,
        public readonly string $state,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            created: (string) ($data->created ?? ''),
            expires: (string) ($data->expires ?? ''),
            id: (string) ($data->id ?? ''),
            last_modified: (string) ($data->last_modified ?? ''),
            price: ($data->price ?? null),
            quantity: (int) ($data->quantity ?? 0),
            seller_id: (int) ($data->seller_id ?? 0),
            skinr_id: (string) ($data->skinr_id ?? ''),
            state: (string) ($data->state ?? ''),
        );
    }
}
