<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class StatusGet extends AbstractEsiDto
{
    public function __construct(
        public readonly int $players,
        public readonly string $server_version,
        public readonly string $start_time,
        public readonly ?bool $vip = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            players: (int) ($data->players ?? 0),
            server_version: (string) ($data->server_version ?? ''),
            start_time: (string) ($data->start_time ?? ''),
            vip: $data->vip ?? null,
        );
    }
}
