<?php

namespace Seatplus\EsiSchema\Responses;

use Seatplus\EsiSchema\AbstractEsiDto;

/**
 * Generated by bin/generate.php — see Seatplus\EsiSchema\GeneratedSpec::COMPATIBILITY_DATE.
 * Do not edit manually — run bin/generate.php instead.
 */
final class UniverseStructuresStructureIdGet extends AbstractEsiDto
{
    public function __construct(
        public readonly string $name,
        public readonly int $owner_id,
        public readonly int $solar_system_id,
        public readonly mixed $position = null,
        public readonly ?int $type_id = null,
    ) {
    }

    public static function from(object $data): static
    {
        return new static(
            name: (string) ($data->name ?? ''),
            owner_id: (int) ($data->owner_id ?? 0),
            solar_system_id: (int) ($data->solar_system_id ?? 0),
            position: $data->position ?? null,
            type_id: $data->type_id ?? null,
        );
    }
}
