<?php

declare(strict_types=1);

namespace Seatplus\EsiSchema;

/**
 * Provenance of this build of seatplus/esi-schema.
 *
 * Generated by bin/generate.php — do not edit manually.
 *
 * The ESI compatibility date is data carried by a release, not a component of the
 * library's version number. Read it from here rather than hard-coding a literal:
 * a transport MUST send COMPATIBILITY_DATE_HEADER: COMPATIBILITY_DATE on every
 * request, so the generated types and the server's response shape cannot disagree.
 */
final class GeneratedSpec
{
    /** ESI compatibility date these types were generated for. */
    public const string COMPATIBILITY_DATE = '2026-08-04';

    /** The header ESI uses to select a compatibility date. */
    public const string COMPATIBILITY_DATE_HEADER = 'X-Compatibility-Date';

    /** sha256 of the OpenAPI document consumed (.esi/openapi.yaml). */
    public const string SPEC_SHA256 = '020e52815678b24dae5843d322258da40abfa2e2c5936f4d317b575b426cb9d9';

    /** Number of generated DTO classes under src/Responses. */
    public const int DTO_COUNT = 282;

    /** Number of generated per-route classes under src/Resources/{Tag}. */
    public const int ROUTE_COUNT = 225;

    /** Number of generated tag wrapper classes under src/Resources. */
    public const int WRAPPER_COUNT = 37;

    private function __construct()
    {
    }
}
